In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data = pd.read_csv('/content/drive/MyDrive/Preprocessed_Data.csv')
predictors = data.iloc[:, :7]
target = data.iloc[:, 7]
data.head()

Sex  Age  Height  Weight  Low Income  Lower Middle Income  \
0    1    5      75      17           1                    0   
1    0    4     101      13           1                    0   
2    0    4      71      17           1                    0   
3    0    3      81      13           0                    0   
4    0    1      79      16           0                    0   

   Upper Middle Income    Status  
0                    0  Stunting  
1                    0  Stunting  
2                    0  Stunting  
3                    1  Stunting  
4                    1  Stunting

In [3]:
print(predictors.head())
print(target.head())

   Sex  Age  Height  Weight  Low Income  Lower Middle Income  \
0    1    5      75      17           1                    0   
1    0    4     101      13           1                    0   
2    0    4      71      17           1                    0   
3    0    3      81      13           0                    0   
4    0    1      79      16           0                    0   

   Upper Middle Income  
0                    0  
1                    0  
2                    0  
3                    1  
4                    1  
0    Stunting
1    Stunting
2    Stunting
3    Stunting
4    Stunting
Name: Status, dtype: object


In [4]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(predictors, target, test_size = 0.3)

In [5]:

from sklearn.svm import SVC
model = SVC()
model.fit(xtrain, ytrain)

SVC()

In [6]:
predict = model.predict(xtest)

In [7]:

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(ytest, predict))
print(accuracy_score(ytest, predict))
print(classification_report(ytest, predict))

[[  0  28   0]
 [  0 211   0]
 [  0  13   0]]
0.8373015873015873
              precision    recall  f1-score   support

  Overweight       0.00      0.00      0.00        28
    Stunting       0.84      1.00      0.91       211
 Underweight       0.00      0.00      0.00        13

    accuracy                           0.84       252
   macro avg       0.28      0.33      0.30       252
weighted avg       0.70      0.84      0.76       252



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [8]:
from sklearn.model_selection import GridSearchCV
parameter = {'C' : [0.1,1,10,100, 1000], 'gamma': [1,0.1,0.01,0.001, 0.00001]}
grid = GridSearchCV(SVC(), param_grid=parameter, verbose=10)
grid.fit(xtrain, ytrain)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5; 1/25] START C=0.1, gamma=1.............................................
[CV 1/5; 1/25] END ..............C=0.1, gamma=1;, score=0.829 total time=   0.1s
[CV 2/5; 1/25] START C=0.1, gamma=1.............................................
[CV 2/5; 1/25] END ..............C=0.1, gamma=1;, score=0.829 total time=   0.1s
[CV 3/5; 1/25] START C=0.1, gamma=1.............................................


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(


[CV 3/5; 1/25] END ..............C=0.1, gamma=1;, score=0.829 total time=   0.1s
[CV 4/5; 1/25] START C=0.1, gamma=1.............................................
[CV 4/5; 1/25] END ..............C=0.1, gamma=1;, score=0.829 total time=   0.1s
[CV 5/5; 1/25] START C=0.1, gamma=1.............................................
[CV 5/5; 1/25] END ..............C=0.1, gamma=1;, score=0.829 total time=   0.1s
[CV 1/5; 2/25] START C=0.1, gamma=0.1...........................................
[CV 1/5; 2/25] END ............C=0.1, gamma=0.1;, score=0.829 total time=   0.0s
[CV 2/5; 2/25] START C=0.1, gamma=0.1...........................................
[CV 2/5; 2/25] END ............C=0.1, gamma=0.1;, score=0.829 total time=   0.0s
[CV 3/5; 2/25] START C=0.1, gamma=0.1...........................................
[CV 3/5; 2/25] END ............C=0.1, gamma=0.1;, score=0.829 total time=   0.0s
[CV 4/5; 2/25] START C=0.1, gamma=0.1...........................................
[CV 4/5; 2/25] END .........

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 1e-05]},
             verbose=10)

In [9]:
grid.best_params_

{'C': 1000, 'gamma': 0.001}

In [10]:
grid.best_estimator_

SVC(C=1000, gamma=0.001)

In [11]:
grid.best_score_

0.8495726495726496

In [12]:
gpredict = grid.predict(xtest)

In [13]:
print(confusion_matrix(ytest, gpredict))
print(classification_report(ytest, gpredict))

[[ 14  14   0]
 [  4 207   0]
 [  0  13   0]]
              precision    recall  f1-score   support

  Overweight       0.78      0.50      0.61        28
    Stunting       0.88      0.98      0.93       211
 Underweight       0.00      0.00      0.00        13

    accuracy                           0.88       252
   macro avg       0.55      0.49      0.51       252
weighted avg       0.83      0.88      0.85       252



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [14]:
from sklearn.svm import SVC
model_final = SVC(C=1000, gamma=0.001)
model_final.fit(xtrain, ytrain)

SVC(C=1000, gamma=0.001)

In [15]:
predictions = model_final.predict(xtest)

In [16]:
print(classification_report(ytest, predictions))
print(accuracy_score(ytest, predictions))

              precision    recall  f1-score   support

  Overweight       0.78      0.50      0.61        28
    Stunting       0.88      0.98      0.93       211
 Underweight       0.00      0.00      0.00        13

    accuracy                           0.88       252
   macro avg       0.55      0.49      0.51       252
weighted avg       0.83      0.88      0.85       252

0.876984126984127


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
