<a href="https://colab.research.google.com/github/444vj/child-malnutrition-01/blob/main/preprocessed_data_dhs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/reduced_features.csv")
df

v113  s116  v212  v190a    v445    v438  v116  v218  v151  v717  ...  \
0       14   2.0    18      1  1994.0  1452.0  31.0     2     1   NaN  ...   
1       12   2.0    28      1  2282.0  1623.0  13.0     3     1   NaN  ...   
2       11   3.0    20      5  2087.0  1529.0  12.0     3     1   NaN  ...   
3       21   3.0    18      2  2445.0  1462.0  41.0     2     1   NaN  ...   
4       21   3.0    21      3  2111.0  1489.0  12.0     2     1   0.0  ...   
...    ...   ...   ...    ...     ...     ...   ...   ...   ...   ...  ...   
2324    14   2.0    16      1  2074.0  1511.0  13.0     7     1   NaN  ...   
2325    14   2.0    28      3  1845.0  1434.0  13.0     2     1   NaN  ...   
2326    21   3.0    32      5  2509.0  1594.0  13.0     2     2   NaN  ...   
2327    21   3.0    20      4  1755.0  1724.0  12.0     2     2   NaN  ...   
2328    12   1.0    18      4  1936.0  1558.0  31.0     2     2   NaN  ...   

      v705  b4  s301  s370b   v437  v024  hidx  v025  v130    m5  
0      NaN   1     1    0.0  421.0    22   1.0     2     1  19.0  
1      NaN   1     1    0.0  601.0    13   3.0     2     3   NaN  
2      NaN   2     1    NaN  488.0    23   1.0     1     1   4.0  
3      NaN   2     1    NaN  523.0     9   1.0     2     1   8.0  
4      4.0   1     1    0.0  468.0    10   1.0     1     2   2.0  
...    ...  ..   ...    ...    ...   ...   ...   ...   ...   ...  
2324   NaN   1     1    0.0  474.0    13   1.0     2     3  12.0  
2325   NaN   2     1    0.0  380.0    20   1.0     2     1  33.0  
2326   NaN   1     1    NaN  638.0    18   NaN     2     1  41.0  
2327   NaN   1     1    0.0  522.0     8   1.0     2     1   9.0  
2328   NaN   2     1    0.0  470.0    33   1.0     2     1  12.0  

[2329 rows x 21 columns]

In [ ]:
df.isnull().sum()

v113        0
s116      100
v212        0
v190a       0
v445       58
v438        1
v116        0
v218        0
v151        0
v717     1934
v701     1934
v705     1934
b4          0
s301        0
s370b     659
v437        1
v024        0
hidx      975
v025        0
v130        0
m5        464
dtype: int64

In [ ]:
df.isna().sum()

v113        0
s116      100
v212        0
v190a       0
v445       58
v438        1
v116        0
v218        0
v151        0
v717     1934
v701     1934
v705     1934
b4          0
s301        0
s370b     659
v437        1
v024        0
hidx      975
v025        0
v130        0
m5        464
dtype: int64

In [ ]:
df = df.dropna()


In [ ]:
df

v113  s116  v212  v190a    v445    v438  v116  v218  v151  v717  ...  \
4       21   3.0    21      3  2111.0  1489.0  12.0     2     1   0.0  ...   
19      12   1.0    30      5  2160.0  1556.0  11.0     1     2   0.0  ...   
27      11   3.0    20      4  1999.0  1552.0  12.0     2     1   6.0  ...   
47      21   3.0    27      5  2584.0  1520.0  12.0     1     1   4.0  ...   
76      21   1.0    20      2  1657.0  1444.0  12.0     2     1   0.0  ...   
...    ...   ...   ...    ...     ...     ...   ...   ...   ...   ...  ...   
2268    12   2.0    21      2  2570.0  1519.0  12.0     3     2   0.0  ...   
2276    21   3.0    19      1  2738.0  1539.0  31.0     3     1   0.0  ...   
2283    97   3.0    22      4  1912.0  1577.0  97.0     1     1   0.0  ...   
2285    11   1.0    18      4  1998.0  1504.0  11.0     1     1   0.0  ...   
2310    97   3.0    20      3  2772.0  1475.0  97.0     3     2   0.0  ...   

      v705  b4  s301  s370b   v437  v024  hidx  v025  v130    m5  
4      4.0   1     1    0.0  468.0    10   1.0     1     2   2.0  
19     4.0   1     1    0.0  523.0     8   1.0     1     1   3.0  
27     5.0   2     1    0.0  482.0     5   1.0     2     1   8.0  
47     4.0   2     1    0.0  597.0    21   1.0     2     1   2.0  
76     7.0   1     1    0.0  346.0    10   1.0     2     1  10.0  
...    ...  ..   ...    ...    ...   ...   ...   ...   ...   ...  
2268   5.0   2     1    0.0  593.0    12   1.0     1    96  29.0  
2276   3.0   2     1    0.0  649.0     9   1.0     2     1   9.0  
2283   6.0   1     1    0.0  476.0    29   1.0     2     1   3.0  
2285   9.0   2     1    0.0  452.0    27   1.0     1     1   7.0  
2310   7.0   1     1    0.0  603.0    10   1.0     2     1   4.0  

[144 rows x 21 columns]

Variables

father's education v701

In [ ]:
print(df['v701'].unique())

[2. 3. 0. 1.]


In [ ]:

print(df['v701'].unique())
print(f'shape of original df = {df.shape}')
df["v701"]=df["v701"].replace({9:8, 0:'No education', 1:'Primary education', 2:'Secondary education', 3:'Higher education'})
indexNames = df[df['v701'] == 8].index
df.drop(indexNames , inplace=True)
print(df['v701'].unique())
print(f'shape of original df = {df.shape}')

[2. 3. 0. 1.]
shape of original df = (144, 21)
['Secondary education' 'Higher education' 'No education'
 'Primary education']
shape of original df = (144, 21)


<ipython-input-9-b516be1d3f76>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["v701"]=df["v701"].replace({9:8, 0:'No education', 1:'Primary education', 2:'Secondary education', 3:'Higher education'})
<ipython-input-9-b516be1d3f76>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(indexNames , inplace=True)


In [ ]:
df['v701'].value_counts()

v701
Secondary education    73
Higher education       27
No education           25
Primary education      19
Name: count, dtype: int64

In [ ]:
df = df.rename(columns={"v701": "Father's Education"})

father's occupation v705

In [ ]:
print(df['v705'].unique())
df['v705']=df['v705'].replace({0:'unemployed',1:'professional',2:'clerical',3:'sales',4:'self employed',5:'Rgri',6:'household',7:'services' ,8:'skilled labour', 99.0:'dont know', 98.0:'dont know'})



[4. 5. 7. 6. 1. 9. 3.]


In [ ]:
# First, print unique values to see the context
print(df['v705'].unique())

# Update the replacement dictionary to include 9
replacement_dict = {
    0: 'unemployed',
    1: 'professional',
    2: 'clerical',
    3: 'sales',
    4: 'self employed',
    5: 'Rgri',
    6: 'household',
    7: 'services',
    8: 'skilled labour',
    9: 'other',  # Assuming 9 represents 'other'
    99.0: 'dont know',
    98.0: 'dont know'
}

# Use .loc to avoid the SettingWithCopyWarning
df.loc[:, 'v705'] = df['v705'].replace(replacement_dict)

# Drop rows where v705 is 'dont know'
df = df[df['v705'] != 'dont know']

# Print unique values and shape to verify the changes
print(df['v705'].unique())
print(f'shape of df after drop = {df.shape}')

# Print the value counts to check the distribution
print(df['v705'].value_counts())


['self employed' 'Rgri' 'services' 'household' 'professional' 9.0 'sales']
['self employed' 'Rgri' 'services' 'household' 'professional' 'other'
 'sales']
shape of df after drop = (144, 21)
v705
services         52
household        46
self employed    14
Rgri             10
other            10
professional      9
sales             3
Name: count, dtype: int64


In [ ]:
df = df.rename(columns={"v705": "Father's Occupation"})

mothers occupation v717

In [ ]:
# First, print unique values to see the context
print(df['v717'].unique())

# Update the replacement dictionary to include 9
replacement_dict = {
    0: 'unemployed',
    1: 'professional',
    2: 'clerical',
    3: 'sales',
    4: 'self employed',
    5: 'Rgri',
    6: 'household',
    7: 'services',
    8: 'skilled labour',
    9: 'other',  # Assuming 9 represents 'other'
    99.0: 'dont know',
    98.0: 'dont know'
}

# Use .loc to avoid the SettingWithCopyWarning
df.loc[:, 'v717'] = df['v717'].replace(replacement_dict)

# Drop rows where v705 is 'dont know'
df = df[df['v717'] != 'dont know']

# Print unique values and shape to verify the changes
print(df['v717'].unique())
print(f'shape of df after drop = {df.shape}')

# Print the value counts to check the distribution
print(df['v717'].value_counts())


[0. 6. 4. 1. 9. 7. 5.]
['unemployed' 'household' 'self employed' 'professional' 'other'
 'services' 'Rgri']
shape of df after drop = (144, 21)
v717
unemployed       111
household         18
Rgri               4
self employed      3
professional       3
services           3
other              2
Name: count, dtype: int64


In [ ]:
df = df.rename(columns={"v717": "Mother's Occupation"})

area v025

In [ ]:

print(df['v025'].unique())
df['v025'] = df['v025'].replace({1:'Urban', 2:'Rural'})
print(df['v025'].unique())
print(df['v025'].value_counts())


[1 2]
['Urban' 'Rural']
v025
Rural    118
Urban     26
Name: count, dtype: int64


In [ ]:
df = df.rename(columns={"v025": "Area"})


religion v130

In [ ]:
print(df['v130'].unique())
df['v130']=df['v130'].replace({1:'Hindu',2:'Muslim',3:'Christian',4:'Sikh',5:'Others',6:'Others',10:'Others' ,9:'Others', 99:'Others', 96:'Others'})


[ 2  1  4  3  6 96]


In [ ]:
print(df['v130'].unique())
print(f'v130 = {df.shape}')


['Muslim' 'Hindu' 'Sikh' 'Christian' 'Others']
v130 = (144, 21)


In [ ]:
df['v130'].value_counts()

v130
Hindu        109
Muslim        21
Christian      8
Others         4
Sikh           2
Name: count, dtype: int64

In [ ]:

df = df.rename(columns={"v130": "Religion"})

caste s116

In [ ]:


df['s116'].unique()

array([3., 1., 4., 2.])

In [ ]:
print(df['s116'].unique())
print(f'shape of original df = {df.shape}')
df["s116"]=df["s116"].replace({8.0:9})
indexNames = df[df['s116'] == 9].index
df.drop(indexNames , inplace=True)
print(df['s116'].unique())
print(f'shape of new df = {df.shape}')

[3. 1. 4. 2.]
shape of original df = (144, 21)
[3. 1. 4. 2.]
shape of new df = (144, 21)


In [ ]:


df['s116']=df['s116'].replace({1:'SC',2:'ST',3:'OBC',4:'Others'})

In [ ]:

df['s116'].value_counts()

s116
OBC       56
SC        34
Others    28
ST        26
Name: count, dtype: int64

In [ ]:
df = df.rename(columns={"s116": "Caste"})

source of drinking water v113

In [ ]:
df['v113'].unique()

array([21, 12, 11, 14, 71, 31, 32, 92, 61, 97, 13, 51, 43])

In [ ]:


df = df.rename(columns={"v113": "Source of drinking water"})

In [ ]:
# Remove missing values (code 99)
df = df[df["Source of drinking water"] != 99]

# Group categories and label them
replacement_dict = {
    10: 1, 11: 1, 12: 1, 13: 1, 14: 1, 20: 1, 21: 1, 30: 1, 31: 1, 41: 1,
    51: 1, 71: 1, 61: 1, 62: 1, 32: 2, 40: 2, 42: 2, 43: 2, 96: 2, 97: 2,
    92: 'Improved'  # Include code 92 in the replacement dictionary
}


# Replace the values in the column
df["Source of drinking water"] = df["Source of drinking water"].replace(replacement_dict)

# Label the categories
df["Source of drinking water"] = df["Source of drinking water"].replace({1: 'Improved', 2: 'Unimproved'})


In [ ]:
# Print shape before dropping missing values
print("Shape before dropping missing values:", df.shape)

# Remove missing values (code 99)
df = df[df["Source of drinking water"] != 99]

# Print shape after dropping missing values
print("Shape after dropping missing values:", df.shape)

# Group categories and label them
replacement_dict = {
    10: 1, 11: 1, 12: 1, 13: 1, 14: 1, 20: 1, 21: 1, 30: 1, 31: 1, 41: 1,
    51: 1, 71: 1, 61: 1, 62: 1, 32: 2, 40: 2, 42: 2, 43: 2, 96: 2, 97: 2
}

# Replace the values in the column
df["Source of drinking water"] = df["Source of drinking water"].replace(replacement_dict)

# Label the categories
df["Source of drinking water"] = df["Source of drinking water"].replace({1: 'Improved', 2: 'Unimproved'})

# Print unique values after processing
print("Unique values after processing:")
print(df['Source of drinking water'].unique())

# Print value counts after processing
print("Value counts after processing:")
print(df['Source of drinking water'].value_counts())


Shape before dropping missing values: (144, 21)
Shape after dropping missing values: (144, 21)
Unique values after processing:
['Improved' 'Unimproved']
Value counts after processing:
Source of drinking water
Improved      129
Unimproved     15
Name: count, dtype: int64


toilet facility v116

In [ ]:
df['v116'].unique()

array([12., 11., 31., 22., 13., 23., 41., 15., 97., 14.])

In [ ]:
df = df.rename(columns={"v116": "Toilet Facility"})

In [ ]:
# Print shape before dropping missing values
print("Shape before dropping missing values:", df.shape)

# Remove missing values (code 99)
df = df[df["Toilet Facility"] != 99]

# Remove rows with missing values
df = df.dropna(subset=["Toilet Facility"])

# Print shape after dropping missing values
print("Shape after dropping missing values:", df.shape)

# Group categories and label them
replacement_dict = {
    10: 1, 11: 1, 12: 1, 13: 1, 14: 1, 15: 1, 20: 2, 21: 2, 22: 2, 23: 2,
    30: 3, 31: 3, 41: 4, 42: 4, 43: 4, 44: 4, 96: 5, 97: 5
}

# Replace the values in the column
df["Toilet Facility"] = df["Toilet Facility"].replace(replacement_dict)

# Label the categories
df["Toilet Facility"] = df["Toilet Facility"].replace({
    1: 'Improved', 2: 'Unimproved', 3: 'No facility',
    4: 'Other', 5: 'Unknown'
})

# Print unique values after processing
print("Unique values after processing:")
print(df['Toilet Facility'].unique())

# Print value counts after processing
print("Value counts after processing:")
print(df['Toilet Facility'].value_counts())


Shape before dropping missing values: (144, 21)
Shape after dropping missing values: (144, 21)
Unique values after processing:
['Improved' 'No facility' 'Unimproved' 'Other' 'Unknown']
Value counts after processing:
Toilet Facility
Improved       77
No facility    34
Unimproved     15
Other          10
Unknown         8
Name: count, dtype: int64


In [ ]:
df['Toilet Facility'].unique()



array(['Improved', 'No facility', 'Unimproved', 'Other', 'Unknown'],
      dtype=object)

In [ ]:
df['Toilet Facility'].value_counts()


Toilet Facility
Improved       77
No facility    34
Unimproved     15
Other          10
Unknown         8
Name: count, dtype: int64

In [ ]:
# Check for NaN values in the "Toilet Facility" column
print(df["Toilet Facility"].isna().sum())


0


mothers age at first birth v212

In [ ]:

df['v212'].unique()

array([21, 30, 20, 27, 32, 19, 23, 25, 24, 17, 18, 22, 15, 26, 29, 28, 16,
       31])

In [ ]:
df['v212'] = pd.cut(df['v212'], bins=[0, 19, 29, 39, 50], include_lowest=True, labels=['<20', '20-29', '30-39', '40 or above'])


In [ ]:
df['v212'].value_counts()

v212
20-29          100
<20             40
30-39            4
40 or above      0
Name: count, dtype: int64

In [ ]:
df = df.rename(columns={"v212": "Mother's age at first birth"})

Sex of child

In [ ]:
df['b4'].unique()


array([1, 2])

In [ ]:
df = df.rename(columns={"b4": "sex of child"})

In [ ]:
df['sex of child']=df['sex of child'].replace({1:'Male',2:'Female'})


In [ ]:
df['sex of child'].value_counts()

sex of child
Female    74
Male      70
Name: count, dtype: int64


wealth index

In [ ]:
df['v190a'].value_counts()

v190a
1    40
2    30
3    25
4    25
5    24
Name: count, dtype: int64

In [ ]:
df = df.rename(columns={"v190a": "wealth index"})

In [ ]:
df['wealth index'] = df['wealth index'].replace({1:'Poorest', 2:'Poorer', 3:'Middle', 4:'Richer', 5:'Richest'})



Months of bf

In [ ]:


df = df.rename(columns={'m5': "months of bf"})

In [ ]:
df['months of bf']=pd.cut(df['months of bf'] ,bins=[0,24, 100], right=False , labels=['<24','>24'] , include_lowest=True)



In [ ]:
df['months of bf'].unique()

['<24', '>24']
Categories (2, object): ['<24' < '>24']

In [ ]:
df['months of bf'].value_counts()

months of bf
<24    107
>24     37
Name: count, dtype: int64


Immunization

In [ ]:
df = df.rename(columns={"s370b": "immunization"})

In [ ]:
df['immunization'] = df['immunization'].replace({0: 'Not immunized', 1: 'Immunized'})


In [ ]:
df['immunization'].value_counts()

immunization
Not immunized    137
Immunized          7
Name: count, dtype: int64

Index to birth history

In [ ]:
df = df.rename(columns={"hidx": "index to birth history"})

In [ ]:
df['index to birth history'].value_counts()


index to birth history
1.0    139
2.0      5
Name: count, dtype: int64

Sex of household head

In [ ]:
df = df.rename(columns={"v151": "sex of household head"})

In [ ]:
df['sex of household head'].value_counts()

sex of household head
1    121
2     23
Name: count, dtype: int64

In [ ]:
df['sex of household head']=df['sex of household head'].replace({1:'Male', 2:'Female'})


no of living children

In [ ]:
df = df.rename(columns={"v218": "number of living children"})


In [ ]:
df['number of living children'].value_counts()

number of living children
1    56
2    46
3    26
4     5
5     4
6     3
0     2
7     1
8     1
Name: count, dtype: int64

currently in union

In [ ]:
df = df.rename(columns={"s301": "currently in union"})


In [ ]:
df['currently in union'] = df['currently in union'].replace({0:'Never married', 1:'Currently married',2:'Married, gauna not performed',3:'Widowed',4:'Divorced',5:'Separated',6:'Deserted'})



In [ ]:
df['currently in union'].value_counts()

currently in union
Currently married    143
Divorced               1
Name: count, dtype: int64

state

In [ ]:
df = df.rename(columns={"v024": "state"})


In [ ]:
# Create a mapping of state codes to state names
state_code_to_name = {
    1: "Jammu & Kashmir",
    2: "Himachal Pradesh",
    3: "Punjab",
    4: "Chandigarh",
    5: "Uttarakhand",
    6: "Haryana",
    7: "Nct Of Delhi",
    8: "Rajasthan",
    9: "Uttar Pradesh",
    10: "Bihar",
    11: "Sikkim",
    12: "Arunachal Pradesh",
    13: "Nagaland",
    14: "Manipur",
    15: "Mizoram",
    16: "Tripura",
    17: "Meghalaya",
    18: "Assam",
    19: "West Bengal",
    20: "Jharkhand",
    21: "Odisha",
    22: "Chhattisgarh",
    23: "Madhya Pradesh",
    24: "Gujarat",
    25: "Dadra & Nagar Haveli And Daman & Diu",
    27: "Maharashtra",
    28: "Andhra Pradesh",
    29: "Karnataka",
    30: "Goa",
    31: "Lakshadweep",
    32: "Kerala",
    33: "Tamil Nadu",
    34: "Puducherry",
    35: "Andaman & Nicobar Islands",
    36: "Telangana",
    37: "Ladakh"
}

# Create a mapping of state names to regions
state_name_to_region = {
    "Jammu & Kashmir": "North_India",
    "Himachal Pradesh": "North_India",
    "Punjab": "North_India",
    "Chandigarh": "North_India",
    "Uttarakhand": "Central_India",
    "Haryana": "North_India",
    "Nct Of Delhi": "North_India",
    "Rajasthan": "North_India",
    "Uttar Pradesh": "Central_India",
    "Bihar": "East_India",
    "Sikkim": "NorthEast_India",
    "Arunachal Pradesh": "NorthEast_India",
    "Nagaland": "NorthEast_India",
    "Manipur": "NorthEast_India",
    "Mizoram": "NorthEast_India",
    "Tripura": "NorthEast_India",
    "Meghalaya": "NorthEast_India",
    "Assam": "NorthEast_India",
    "West Bengal": "East_India",
    "Jharkhand": "East_India",
    "Odisha": "East_India",
    "Chhattisgarh": "Central_India",
    "Madhya Pradesh": "Central_India",
    "Gujarat": "West_India",
    "Dadra & Nagar Haveli And Daman & Diu": "West_India",
    "Maharashtra": "West_India",
    "Andhra Pradesh": "South_India",
    "Karnataka": "South_India",
    "Goa": "West_India",
    "Lakshadweep": "South_India",
    "Kerala": "South_India",
    "Tamil Nadu": "South_India",
    "Puducherry": "South_India",
    "Andaman & Nicobar Islands": "South_India",
    "Telangana": "South_India",
    "Ladakh": "North_India"
}

# Replace numeric state codes with state names
df['state'] = df['state'].replace(state_code_to_name)

# Replace state names with corresponding regions
df['state'] = df['state'].replace(state_name_to_region)




In [ ]:
df['state'].value_counts()


state
Central_India      42
East_India         40
North_India        26
NorthEast_India    16
South_India        13
West_India          7
Name: count, dtype: int64

mother's weight in kgs(1 decimal)

In [ ]:
df = df.rename(columns={"v437": "mother's weight"})


In [ ]:
import numpy as np
# First, print unique values to see the context
print(df["mother's weight"].unique())

# Update the replacement dictionary to include specific codes
# Update the replacement dictionary to include specific codes
replacement_dict = {
    9994: np.nan,
    9995: np.nan,
    9996: np.nan,
    9999: np.nan
}

# Replace specific codes with NaN in the 'mother's weight' column
df['mother\'s weight'] = df['mother\'s weight'].replace(replacement_dict)

# Drop rows with NaN values in the 'mother's weight' column
df = df.dropna(subset=['mother\'s weight'])

# Print unique values and shape to verify the changes
print(df['mother\'s weight'].unique())
print(f'Shape of df after dropping rows = {df.shape}')

# Print the value counts to check the distribution
print(df['mother\'s weight'].value_counts())


[468. 523. 482. 597. 346. 464. 485. 653. 392. 589. 497. 681. 458. 381.
 584. 367. 614. 579. 395. 496. 437. 512. 500. 549. 382. 489. 420. 670.
 413. 404. 409. 569. 470. 660. 428. 425. 529. 557. 389. 499. 573. 574.
 477. 471. 387. 376. 460. 667. 643. 439. 411. 765. 685. 418. 528. 507.
 369. 473. 645. 429. 364. 446. 481. 441. 692. 352. 493. 679. 525. 445.
 402. 433. 466. 635. 455. 592. 467. 563. 416. 430. 397. 448. 383. 562.
 472. 375. 483. 559. 628. 602. 484. 358. 494. 633. 407. 652. 454. 414.
 463. 426. 495. 513. 506. 431. 475. 522. 601. 558. 536. 593. 649. 476.
 452. 603.]
[468. 523. 482. 597. 346. 464. 485. 653. 392. 589. 497. 681. 458. 381.
 584. 367. 614. 579. 395. 496. 437. 512. 500. 549. 382. 489. 420. 670.
 413. 404. 409. 569. 470. 660. 428. 425. 529. 557. 389. 499. 573. 574.
 477. 471. 387. 376. 460. 667. 643. 439. 411. 765. 685. 418. 528. 507.
 369. 473. 645. 429. 364. 446. 481. 441. 692. 352. 493. 679. 525. 445.
 402. 433. 466. 635. 455. 592. 467. 563. 416. 430. 397. 448. 383.

mother's height

In [ ]:
df = df.rename(columns={"v438": "mother's height"})


In [ ]:
import numpy as np
# First, print unique values to see the context
print(df["mother's height"].unique())

# Update the replacement dictionary to include specific codes
# Update the replacement dictionary to include specific codes
replacement_dict = {
    9994: np.nan,
    9995: np.nan,
    9996: np.nan,
    9999: np.nan
}

# Replace specific codes with NaN in the 'mother's weight' column
df['mother\'s height'] = df['mother\'s height'].replace(replacement_dict)

# Drop rows with NaN values in the 'mother's weight' column
df = df.dropna(subset=['mother\'s height'])

# Print unique values and shape to verify the changes
print(df['mother\'s height'].unique())
print(f'Shape of df after dropping rows = {df.shape}')

# Print the value counts to check the distribution
print(df['mother\'s height'].value_counts())


[1489. 1556. 1552. 1520. 1444. 1522. 1524. 1578. 1505. 1645. 1497. 1677.
 1573. 1574. 1311. 1476. 1586. 1465. 1538. 1475. 1609. 1594. 1392. 1513.
 1535. 1511. 1453. 1527. 1577. 1510. 1491. 1404. 1486. 1519. 1493. 1512.
 1507. 1467. 1523. 1480. 1496. 1639. 1579. 1521. 1630. 1634. 1532. 1572.
 1482. 1563. 1485. 1464. 1461. 1395. 1449. 1427. 1414. 1484. 1501. 1530.
 1551. 1626. 1564. 1434. 1537. 1421. 1543. 1555. 1456. 1568. 1602. 1571.
 1399. 1481. 1499. 1287. 1435. 1462. 1541. 1514. 1488. 1342. 1593. 1479.
 1495. 1416. 1492. 1473. 1545. 1504. 1554. 1643. 1517. 1558. 1412. 1546.
 1557. 1439. 1500. 1526. 1459. 1375. 1415. 1436. 1595. 1587. 1539.]
[1489. 1556. 1552. 1520. 1444. 1522. 1524. 1578. 1505. 1645. 1497. 1677.
 1573. 1574. 1311. 1476. 1586. 1465. 1538. 1475. 1609. 1594. 1392. 1513.
 1535. 1511. 1453. 1527. 1577. 1510. 1491. 1404. 1486. 1519. 1493. 1512.
 1507. 1467. 1523. 1480. 1496. 1639. 1579. 1521. 1630. 1634. 1532. 1572.
 1482. 1563. 1485. 1464. 1461. 1395. 1449. 1427. 1414. 1

In [ ]:
import pandas as pd

# Assuming your dataset is stored in a pandas DataFrame called 'df'
# with columns 'mothers_height_cm' and 'mothers_weight_kg'

# Calculate BMI
df['mothers_bmi'] = df['mother\'s weight'] / ((df['mother\'s height'] / 100) ** 2)

# Round BMI to 1 decimal place
df['mothers_bmi'] = df['mothers_bmi'].round(1)




In [ ]:


# Display the shape of the DataFrame
print("Shape of DataFrame:", df.shape)

# Display the value counts of the 'mothers_bmi' column
print("\nValue counts of 'mothers_bmi' column:")
print(df['mothers_bmi'].value_counts())


Shape of DataFrame: (144, 22)

Value counts of 'mothers_bmi' column:
mothers_bmi
2.2    24
2.0    19
1.8    16
2.1    13
2.3    11
1.7    11
1.9    10
2.4     7
2.5     6
2.8     5
2.6     5
1.6     5
2.7     5
2.9     3
3.3     1
1.5     1
3.0     1
1.4     1
Name: count, dtype: int64


In [ ]:


df.shape

(144, 22)

In [ ]:
df

Source of drinking water Caste Mother's age at first birth wealth index  \
4                    Improved   OBC                       20-29       Middle   
19                   Improved    SC                       30-39      Richest   
27                   Improved   OBC                       20-29       Richer   
47                   Improved   OBC                       20-29      Richest   
76                   Improved    SC                       20-29       Poorer   
...                       ...   ...                         ...          ...   
2268                 Improved    ST                       20-29       Poorer   
2276                 Improved   OBC                         <20      Poorest   
2283               Unimproved   OBC                       20-29       Richer   
2285                 Improved    SC                         <20       Richer   
2310               Unimproved   OBC                       20-29       Middle   

        v445  mother's height Toilet Facility  number of living children  \
4     2111.0           1489.0        Improved                          2   
19    2160.0           1556.0        Improved                          1   
27    1999.0           1552.0        Improved                          2   
47    2584.0           1520.0        Improved                          1   
76    1657.0           1444.0        Improved                          2   
...      ...              ...             ...                        ...   
2268  2570.0           1519.0        Improved                          3   
2276  2738.0           1539.0     No facility                          3   
2283  1912.0           1577.0         Unknown                          1   
2285  1998.0           1504.0        Improved                          1   
2310  2772.0           1475.0         Unknown                          3   

     sex of household head Mother's Occupation  ... sex of child  \
4                     Male          unemployed  ...         Male   
19                  Female          unemployed  ...         Male   
27                    Male           household  ...       Female   
47                    Male       self employed  ...       Female   
76                    Male          unemployed  ...         Male   
...                    ...                 ...  ...          ...   
2268                Female          unemployed  ...       Female   
2276                  Male          unemployed  ...       Female   
2283                  Male          unemployed  ...         Male   
2285                  Male          unemployed  ...       Female   
2310                Female          unemployed  ...         Male   

     currently in union   immunization mother's weight            state  \
4     Currently married  Not immunized           468.0       East_India   
19    Currently married  Not immunized           523.0      North_India   
27    Currently married  Not immunized           482.0    Central_India   
47    Currently married  Not immunized           597.0       East_India   
76    Currently married  Not immunized           346.0       East_India   
...                 ...            ...             ...              ...   
2268  Currently married  Not immunized           593.0  NorthEast_India   
2276  Currently married  Not immunized           649.0    Central_India   
2283  Currently married  Not immunized           476.0      South_India   
2285  Currently married  Not immunized           452.0       West_India   
2310  Currently married  Not immunized           603.0       East_India   

      index to birth history   Area  Religion months of bf mothers_bmi  
4                        1.0  Urban    Muslim          <24         2.1  
19                       1.0  Urban     Hindu          <24         2.2  
27                       1.0  Rural     Hindu          <24         2.0  
47                       1.0  Rural     Hindu          <24         2.6  
76                       1.0  Rural     Hindu   

In [ ]:
df.to_csv('preprocessed_data.csv')